project:
  type: website
  output-dir: docs

website:
  title: "Command line workshop"
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [issue]
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
  page-footer:
    left: "2022, Jelmer Poelstra"
    right:
      - icon: github
        href: https://github.com/

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

