project:
  type: website
  output-dir: docs

website:
  title: "Command line workshop '22"
  repo-url: https://github.com/mcic-osu/cl-workshop-22
  repo-actions: [issue]
  navbar:
    search: true
    right:
      - href: schedule.qmd
        text: Schedule
  page-footer:
    left: "2022, Jelmer Poelstra"
    right:
      - icon: github
        href: https://github.com/mcic-osu/cl-workshop-22

format:
  html:
    theme:
      light: lumen
      dark: darkly
    css: styles.css
    toc: true

