project:
  type: website
  output-dir: docs

website:
  title: "Command line workshop '22"
  repo-url: https://github.com/mcic-osu/cl-workshop-22
  repo-actions: [issue]
  navbar:
    search: true
    right:
      - text: "Additional info"
        menu:
          - href: info/info.qmd
            text: Practical Workshop Info
          - href: about.qmd
            text: General Workshop Info / Signing Up
    left:
      - text: "Day 1"
        menu:
          - href: sessions/workshop-intro.qmd
            text: 1. Workshop Intro
          - href: sessions/osc-intro.qmd
            text: 2. OSC Intro
          - href: sessions/vscode.qmd
            text: 3. VS Code
          - href: sessions/shell-intro.qmd
            text: 4. The Unix Shell
      - text: "Day 2"
        menu:
          - href: sessions/scripting-prep.qmd
            text: 5. Variables, Loops and Conditionals
          - href: sessions/shell-scripting.qmd
            text: 6. Shell Scripting
          - href: sessions/software.qmd
            text: 7. Software at OSC
      - text: "Day 3"
        menu:
          - href: sessions/slurm.qmd
            text: 8. SLURM
          - href: sessions/examples.qmd
            text: 9. Example Compute Jobs
  page-footer:
    left: "2022, Jelmer Poelstra"
    right:
      - icon: github
        href: https://github.com/mcic-osu/cl-workshop-22

format:
  html:
    theme:
      light: lumen
      dark: darkly
    css: styles.css
    toc: true

