---
title: "Practical Workshop Information"
highlight-style: oblivion
---

```{r knitr_options, echo=FALSE}
knitr::opts_chunk$set(eval = FALSE,
                      class.output = "bash-out")
```

-----

## Locations and links

- **Columbus**: Aronoff Laboratory, room 104 (instructor: Mike Sovic)
- **Wooster**: Selby Hall, room 203 ~~(instructor: Jelmer Poelstra)~~
- **Zoom**: email us for the link! (instructor: Jelmer Poelstra)
- [Google Doc for sharing links and code, and for non-urgent questions](https://docs.google.com/document/d/1M_BSRtnG3QYjntpgxbMENr_ZJGrA35B1e7E0Dn0hK5Q/edit?usp=sharing)

## Computer Setup

#### Your computer

Since we will be working entirely at the Ohio Supercomputer Center (OSC),
and will be doing so **through our internet browsers**:

- You won't need to install anything
- Any operating system will work
- You won't need an especially powerful machine
  (though browsers, especially in combination with Zoom, can use their fair
  share of memory).

If you're attending **in person**, you will need to bring a _laptop_.
You can watch the presentation on a big screen in the room,
which will make it easier to code along (see below).
You won't need to connect to the Zoom call.

If you're attending **via Zoom**, we would recommend a _two-monitor setup_.
This is because much of the time,
you need to be able to simultaneously see the instructor's screen via Zoom
as well as your own browser window.

#### OSC account and project

To work with OSC resources, we need access to an "OSC project".
We will be using the project `PAS2250` during the workshop,
and all participants  will be added to that project.
If you don't yet have a personal OSC account,
you will receive an invitation to create one when you've been added to the project.

#### Google Doc

We'll use
**[this Google Doc](https://docs.google.com/document/d/1M_BSRtnG3QYjntpgxbMENr_ZJGrA35B1e7E0Dn0hK5Q/edit?usp=sharing)**
for sharing links and code, and for non-urgent questions.

## Miscellaneous info

#### Expect to participate!

The modules will be a mixture of lectures that include
"**participatory live-coding**"
(also called "_code-along_"; with the instructor slowly demonstrating and
participants expected to follow along for themselves)
and small **single-person exercises**
(we won't be doing breakout rooms / groups).
Therefore, be prepared to actively participate during much of the workshop!

#### Example data

We will mainly use a set of
**`FASTQ` files from a**
**[published RNAseq experiment](https://www.nature.com/articles/sdata2018290)**
as example data.
(It may be worth emphasizing that the exact data type matters relatively little
for the purposes of our workshop,
since we focus on foundational skills and not specific genomic analyses.)

If you have any **genomic data of your own**,
you can bring it along and you should be able to experiment a bit with it
during our second session on Friday afternoon.
If this is a large dataset (say, >10GB),
uploading it to OSC will take some time.
You could try to start this after Wednesday's sessions,
when you've had some background on this.
Alternatively, you can contact the instructors about this prior to the workshop.

#### Participants

We're expecting up to 14 people in Wooster, 14 in Columbus, and 6 via Zoom.
